# lifesub-web/deployment/manifest/services/lifesub-web-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: lifesub-web
spec:
  selector:
    app: lifesub-web
  ports:
  - port: 80
    targetPort: 18080
  type: LoadBalancer